/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferStrategy;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JFrame;
/**
 *
 * @author Carlos
 */
public class PantallaBienvenida extends javax.swing.JFrame {

    public boolean comandoCorrecto = false;
    private int windowWidth = 1920;
    private int windowHeight = 1080;
    private String direccion;
    private int menuWidth = 1920;
    private int menuHeight = 1080;
    public BufferStrategy bs;
    JFrame j;
    private boolean mover = true, flag = true;
    private char mov;
    /**
     * Creates new form PantallaBienvenida
     */
    public PantallaBienvenida() {
        initComponents();
        setSize(windowWidth + menuWidth, windowHeight);
        setResizable(false);
        setLocation(75, 50);
        setVisible(true);
        this.jPanel1.setSize(menuWidth, menuHeight);
        this.jPanel1.setVisible(true);
        bs = this.getBufferStrategy();
setFocusable(true);
        Imagen imagen = new Imagen();
        jPanel1.add(imagen).repaint();
        j = new JFrame();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(1576, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VentanaJuego vj = new VentanaJuego("lalala", 800, 400);
        vj.iniciarJuego();
        //PantallaPrincipal p = new PantallaPrincipal();
//        JFrame p= new JFrame();
//        try {
//            p.setTitle("Diablito");
//            p.setSize(1024, 780);
//            p.setResizable(false);
//            p.setVisible(true);
//            p.add(new PanelInformacion());
//            p.setLocationRelativeTo(null);
//            p.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            this.dispose();
//        } catch (IOException e) {
//            System.out.println(e.getMessage());
//        }
//Juego juego = new Juego();
//mov = 'p';
//while(true){
//        try {
//            //j.getContentPane().removeAll();
//            if(flag){
//            j.setTitle("Maze");
//            j.setSize(1920, 1080);
//            
//            j.add(new Board(juego, mov));
//            j.setLocationRelativeTo(null);
//            j.setVisible(true);
//            j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            this.dispose();
//            //Debo habilitar el keylistener
//            if(mover){
//            String ax = JOptionPane.showInputDialog("Ingrese un comando: ");
//                    JOptionPane.showMessageDialog(null, "El comando ingresado es: " + ax);
//                     mov = ax.charAt(0);
//                     if(ax.equals("MOVER")){
//                         mover = false;
//                         flag = false;
//                     }
//            }
//            else
//                flag = false;
//            }
//        } catch (IOException e) {
//            System.out.println(e.getMessage());
//            
//        }
//}
    }//GEN-LAST:event_jButton1ActionPerformed

public void    keyPressed (KeyEvent e){
    System.out.println("asdasdasakakjkakakakakakkakakakkakakakka");
}

public void keyReleased(KeyEvent e) {
    System.out.println("lasklhdjklashdjkashdjkashdjkas");
    if(!mover){
        
        if(e.getKeyCode()== KeyEvent.VK_D){
            System.out.println("lasklhdjklashdjkashdjkashdjkas");
            flag = true;
            mov = 'd';
        }
        else if(e.getKeyCode()== KeyEvent.VK_A){
            flag = true;
            mov = 'a';
        }
        else if(e.getKeyCode()== KeyEvent.VK_S){
            flag = true;
            mov = 's';
        }
        else if(e.getKeyCode()== KeyEvent.VK_W){
            flag = true;
            mov = 'w';
        }
    }

    }

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    public class Imagen extends javax.swing.JPanel {

        public Imagen() {

            this.setSize(1920, 1080); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics
        public void paint(Graphics grafico) {
            Dimension height = getSize();

            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/imagenes/inicio.png"));

            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);

            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
